## -------------------------------------------------------------------------------------
# Output saving options
## -------------------------------------------------------------------------------------
save_wsi_mask: False
save_annotations: False
save_nuclei_meta: True
save_nuclei_props: True

## -------------------------------------------------------------------------------------
# Run configurations
## -------------------------------------------------------------------------------------
independent_tile_assignment: False # see line 900, MuTILsWSIRunner.py
N_preprocesses: 10
N_postprocesses: 40
_debug: False